### ISSUE TITLE
Signature.fromBase64 throws error "Wanted sequence 30, got A4"

### ISSUE THREAD

**Issue by ritesh09** [starkbank/ecdsa-dotnet#23]
Not sure  what is going wrong and i tried a lot but couldn't solve this issue. 

I have a file which contains signature and data in json format. Signature is base64 encoded string. When I try to create Signature object using Signature.FromBase64, it throws the error "wanted sequence 30, got A4".  Sample code:

```
var object = System.Text.Json.JsonDocument.Parse(r.ReadToEnd());
data = object.RootElement.GetProperty("data").ToString();
base64Signature = object.RootElement.GetProperty("key").ToString();
Signture signature = Signature.fromBase64(base64Signature);
```
Any lead in this matter would help. I am sure i am missing something somewhere. 

Thanks,
Ritesh

**Comment by mahgo** [comment]
I'm having a similar issue, did you work this out @ritesh09?

**Comment by cdottori-stark** [comment]
Hello, could you provide an example of a signature sample that is raising this exception?

**Comment by mahgo** [comment]
Hi @cdottori-stark 

The exact exception message I'm getting is `wanted sequence 30, got 4D`.

I'm implementing Google AdMob server-sider verification, as per https://developers.google.com/admob/unity/ssv

An example signature string is `MEQCIGOnSjGuPJOxFm7bL0Bb4cIu58FyFqNiOHk3D3YuWWp4AiBSkbpt_DVkV9TYzTfiRm-rpGMCTc8HxCPSmrN_osyv7g`, which I turn into a byte[] via `byte[] signatureBytes = Encoding.UTF8.GetBytes(signature);` then pass into `Signature signature = Signature.fromDer(signatureBytes);` which throws the exception.

**Comment by cdottori-stark** [comment]
"MEQCIGOnSjGuPJOxFm7bL0Bb4cIu58FyFqNiOHk3D3YuWWp4AiBSkbpt_DVkV9TYzTfiRm-rpGMCTc8HxCPSmrN_osyv7g" looks a lot like a base64 string, but with the url-safe encoding instead of the standard one.

Converting the '-' to '+' and the '_' to '/' and adding the necessary padding (==), we get the usual base64 string "MEQCIGOnSjGuPJOxFm7bL0Bb4cIu58FyFqNiOHk3D3YuWWp4AiBSkbpt/DVkV9TYzTfiRm+rpGMCTc8HxCPSmrN/osyv7g==", which is correctly parsed by the Signature.fromBase64() method.

@mahgo, can you confirm this adjusted signature validates the expected message?

**Comment by mahgo** [comment]
Hi @cdottori-stark, thanks for your help. For that particular string, it successfully creates the Signature. It fails to validate, but that's probably an issue with the message I'm passing in. I'll work this out after sorting out the below issues first. 

I've found that some signatures I get (from Google) are a different length, such as `MEYCIQCubIRjkR0gWHQuSKli2JyMNwoc-MafUbWUIAB4W-dG1QIhAIwxx3lgS2samfrlMUdKbg9uByGjRrMS9yBf90hCNG7P`, which gives me this exception:
`System.FormatException : Invalid length for a Base-64 char array or string.` 

And another example I have here `MEUCIAevD8MLU1FnnJvcX5hIaHpyy1pLd80dJLie-ZoLj7erAiEAxu699LQoKNb1OAcL3LaFPrLl5R3uM6S0ojIExSaU0Ac` gives 
`System.OverflowException : Arithmetic operation resulted in an overflow.`

For reference, here's the rough code I have to convert the string to the base64 string:
```
string signatureBase64 = signatureString.Replace('_', '/').Replace('-', '+') + "==";
Signature signature = Signature.fromBase64(signatureBase64);
```

**Comment by mahgo** [comment]
I just got a response back from Google and it looks like their examples use this function https://github.com/google/tink/blob/3e7682054a4f8e4d956e590c0e13309ab1dc2eba/java_src/src/main/java/com/google/crypto/tink/subtle/Base64.java#L164 

Should I try porting it over, or is there something equivalent in this library or another C# library?

**Comment by cdottori-stark** [comment]
Hi @mahgo

In Base64 encoding, the length of an output-encoded String must be a multiple of three. The encoder might add one or two padding characters (=) at the end of the output as needed in order to meet this requirement, so it won't always be necessary to add a "==" to the end of the string, as that might actually break the base64 string.

It is very likely that another C# library is able to make this url-safe to standard base64 translation for you, or even to bytes directly (allowing you to use the fromDer() method), but we haven't used any of them ourselves, so far.

**Comment by mahgo** [comment]
Hi @cdottori-stark,

Thanks for that, that cleared things up for me re base64. Here's my final rough function for getting the signature:
```
public Signature GetSignature(string signatureString)
{
    string signatureBase64 = signatureString.Replace('_', '/').Replace('-', '+');
    switch (signatureBase64.Length % 3)
    {
        case 1:
            signatureBase64 += "==";
            break;
        case 2:
            signatureBase64 += "=";
            break;
    }

    Signature signature = Signature.fromBase64(signatureBase64);
    return signature;
}
```

And I can now confirm that the signature verifies the message - turns out I had a substring issue with getting my message to verify, which is now resolved and verify is returning true.

Thanks again for your help!

**Comment by cdottori-stark** [comment]
No problem, glad to help!
